 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author jasmi
 */
public class add_payment extends javax.swing.JFrame {

    /**
     * Creates new form add_payment
     */
    String username = "";
     String idstaff = "";
    public add_payment(String user,String staffid) {
        initComponents();
        setTitle("Health Care Fees Payment System"); 
         this.setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        fillcombopayment();
        username = user;
        idstaff = staffid;
        txtmadeby.setText(idstaff);
      
    }
    
    private void fillcombopayment() {
        String role = "Student";
        File file = new File("Charges.txt");
        
        Scanner sc;
            try {    
                sc = new Scanner(file);
                
       String temp;
       boolean found = false;
       while(sc.hasNext() && !found /*the system will stop running while it found the correct username and password*/){
           temp = sc.nextLine(); //read a line of text from file
           String[] tempArr;
            tempArr = temp.split (",");

               if (role.equals(tempArr[6])){
              //needed value in array
                String valueneeded = tempArr[0];
                String [] column = valueneeded.split(",");
                   for (String column1 : column) {
                   cbxpaymentid.addItem(column1);
               }
               }             
            }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(check_schedule.class.getName()).log(Level.SEVERE, null, ex);
            }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtfee = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lbltitle1 = new javax.swing.JLabel();
        lblcourse = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        btngeneratereceipt = new javax.swing.JButton();
        btnreturn = new javax.swing.JButton();
        lbltrainer = new javax.swing.JLabel();
        btnprintreceipt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        txtpay = new javax.swing.JTextField();
        lblpay = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        lblbalance = new javax.swing.JLabel();
        txtcourse = new javax.swing.JTextField();
        txttrainer = new javax.swing.JTextField();
        txtmonth = new javax.swing.JTextField();
        cbxpaymentid = new javax.swing.JComboBox<>();
        lblid1 = new javax.swing.JLabel();
        lblstdid = new javax.swing.JLabel();
        txtstdid = new javax.swing.JTextField();
        btncalculate = new javax.swing.JButton();
        lblstdid1 = new javax.swing.JLabel();
        txtmadeby = new javax.swing.JTextField();
        btnviewpayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtfee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 99, 71));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Make");

        lbltitle1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle1.setText("Payment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblcourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcourse.setText("Course");

        lblgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblgender.setText("Month");

        lbldob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldob.setText("Fee");

        btngeneratereceipt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btngeneratereceipt.setText("Generate receipt");
        btngeneratereceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratereceiptActionPerformed(evt);
            }
        });

        btnreturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        lbltrainer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltrainer.setText("Trainer");

        btnprintreceipt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnprintreceipt.setText("Print Receipt");
        btnprintreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintreceiptActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        txtpay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblpay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblpay.setText("Pay Amount");

        txtbalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblbalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblbalance.setText("Balance");

        txtcourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txttrainer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtmonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbxpaymentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxpaymentidActionPerformed(evt);
            }
        });

        lblid1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblid1.setText("Payment ID");

        lblstdid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblstdid.setText("Student ID");

        txtstdid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btncalculate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncalculate.setText("Calculate");
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });

        lblstdid1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblstdid1.setText("Made by");

        txtmadeby.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnviewpayment.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnviewpayment.setText("View Payment");
        btnviewpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btngeneratereceipt)
                        .addGap(18, 18, 18)
                        .addComponent(btnprintreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltrainer)
                                    .addComponent(lblcourse)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbldob)
                                        .addComponent(lblgender)))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txttrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblid1)
                                .addGap(50, 50, 50)
                                .addComponent(cbxpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblpay)
                                    .addGap(54, 54, 54)
                                    .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblbalance)
                                    .addGap(54, 54, 54)
                                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblstdid)
                                .addGap(50, 50, 50)
                                .addComponent(txtstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblstdid1)
                                .addGap(50, 50, 50)
                                .addComponent(txtmadeby, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncalculate)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnviewpayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnreturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnviewpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstdid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtmadeby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblid1)
                            .addComponent(cbxpaymentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstdid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtstdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblcourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltrainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblgender))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttrainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldob))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbalance)
                            .addComponent(btncalculate))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btngeneratereceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnprintreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        new staff_button(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnreturnActionPerformed

    private void cbxpaymentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxpaymentidActionPerformed
        String payment = cbxpaymentid.getSelectedItem().toString();
        String filepath = "C:\\Users\\jasmi\\Documents\\NetBeansProjects\\JP\\Charges.txt";
        File file = new File(filepath);
        
        BufferedReader br;
        String strLine;
        try {
            br = new BufferedReader (new FileReader(file));

                try {
                    while((strLine=br.readLine())!=null){
                        Object[] details = strLine.lines().toArray();
                        for (Object detail : details) {
                            String line = detail.toString().trim();
                            String[] row = line.split(",");

                            if (payment.equals(row[0])) {
                                txtstdid.setText(row[1]);
                                txtcourse.setText(row[2]);
                                txttrainer.setText(row[3]);
                                txtmonth.setText(row[4]);
                                txtfee.setText(row[5]);
                                
                                txtmadeby.setEditable(false);
                                txtstdid.setEditable(false);
                                txtcourse.setEditable(false);
                                txttrainer.setEditable(false);
                                txtmonth.setEditable(false);
                                txtfee.setEditable(false);
                                txtbalance.setEditable(false);
                               
                                
                            }
                        }
                        
                    }   } catch (IOException ex) {
                    Logger.getLogger(check_schedule.class.getName()).log(Level.SEVERE, null, ex);
                }

        } catch (IOException ex) {
            Logger.getLogger(check_schedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxpaymentidActionPerformed

    private void btngeneratereceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeneratereceiptActionPerformed
        String payment1 = cbxpaymentid.getSelectedItem().toString();
        if (txtpay.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the pay amount", "Incomplete Student Pay Amount", JOptionPane.ERROR_MESSAGE);
            //set cursor to the textbox
            txtpay.requestFocus();  
        }
        else if (txtbalance.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane, "Please enter the calculate the balance", "Incomplete Student Pay Balance", JOptionPane.ERROR_MESSAGE);
        //set cursor to the textbox
        txtpay.requestFocus();  
            
        }
        else{
            try{
            add_payment1 pay = new add_payment1(txtmadeby.getText(),payment1,txtstdid.getText(),txtcourse.getText(), txttrainer.getText(),txtmonth.getText(),txtfee.getText(),txtpay.getText(),txtbalance.getText());
           
            FileWriter myFile = new FileWriter("Payment.txt",true);
            PrintWriter pw = new PrintWriter(myFile);
            pw.println(pay.getMadeby() + "," + pay.getPaymentID() + "," + pay.getStudentID()+ "," + pay.getStudentcourse() +  "," + pay.getStudenttrainer()+ "," + pay.getStudentmonth()+ "," + pay.getStudentfee()+ "," + pay.getStudentpayamount()+ "," + pay.getStudentbalance()+ "," + "Student");
            pw.close();
             //JOptionPane.showMessageDialog(rootPane, "Student payment added", "Add Successful", JOptionPane.INFORMATION_MESSAGE);
     // After closing the previous message dialog, ask user whether
     // to continue adding
        
        //receipt
        area.setText("***************************************************************************************\n");
        area.setText(area.getText()+"*                     ASIA PACIFIC UNIVERSITY (APU)                    *\n");
        area.setText(area.getText()+"*                          Fees Receipt System                         *\n");
        area.setText(area.getText()+"************************************************************************\n");

        Date obj = new Date();

        String date = obj.toString();

        area.setText(area.getText()+"\n"+date+ "\n\n");
        area.setText(area.getText()+"                    Payment made by : "+txtmadeby.getText()+"\n\n");
        area.setText(area.getText()+"                    Payment ID : "+cbxpaymentid.getSelectedItem()+"\n\n");
        area.setText(area.getText()+"                    Student ID : "+txtstdid.getText()+"\n\n");
        area.setText(area.getText()+"                    Student Course : "+txtcourse.getText()+"\n\n");
        area.setText(area.getText()+"                    Trainer Name : "+txttrainer.getText()+"\n\n");
        area.setText(area.getText()+"                    Month : "+txtmonth.getText()+"\n\n");
        area.setText(area.getText()+"                    Fees Amount : "+txtfee.getText()+"\n\n");
        area.setText(area.getText()+"                    Pay Amount : "+txtpay.getText()+"\n\n");
        area.setText(area.getText()+"                    Payment Balance : "+txtbalance.getText()+"\n\n");
        area.setText(area.getText()+"\n                                     Signature");
            
         
        //delete charges 
       String removeTerm = cbxpaymentid.getSelectedItem().toString(); 

        ArrayList <String> tempArray = new ArrayList <>();

        try{
            File file = new File("Charges.txt");
            file.createNewFile();
            Scanner sc = new Scanner(file);
            String data;
            
            
            while((data = sc.nextLine()) != null){
                String[] tempData = data.split(",");
                if(!removeTerm.equals(tempData[0])){
                    tempArray.add(data);
                    
                }
                
            }
            sc.close();
        }catch(Exception ex){
            ex.toString();
        }

        try{
            try(PrintWriter pr = new PrintWriter("Charges.txt")){
                for(String newFile : tempArray){
                    pr.println(newFile);
                }
                pr.close();
                
                JOptionPane.showMessageDialog(rootPane, "Your charges has been paid", "Pay Successful", JOptionPane.INFORMATION_MESSAGE);
                
            }
        }catch(Exception ex){
            ex.toString();
        }
        
           int YesNo = JOptionPane.YES_OPTION;
         if (JOptionPane.showConfirmDialog (null, "Do you want to make another payment?","Add New", YesNo) == JOptionPane.YES_OPTION){
             clearFields();   
                   btngeneratereceipt.setEnabled(true);
                   btnprintreceipt.setEnabled(false);
                    }
                    else {
                    btnprintreceipt.setEnabled(true);
                    btngeneratereceipt.setEnabled(false);
                    }  
            }
            catch (IOException ex){
                JOptionPane.showMessageDialog(rootPane, ex.toString());
            }
        }
    }//GEN-LAST:event_btngeneratereceiptActionPerformed

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed

        //get pay from textbox
        double pay = Double.parseDouble(txtpay.getText());
        //get fee from textbox
        double fee = Double.parseDouble(txtfee.getText());
        //calculate of the balance
        double balance = pay - fee;
        
        Scanner sc = new Scanner (System.in);
        // TODO code application logic here      
        
        //value format
        DecimalFormat df = new DecimalFormat("#,###");
         //read the input
        System.out.println (df.format(fee));
        System.out.println (df.format(pay));
        System.out.println (df.format(balance));
        //display balance in textbox
        txtbalance.setText("RM" + df.format(balance));
       
               
    }//GEN-LAST:event_btncalculateActionPerformed

    private void btnprintreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintreceiptActionPerformed
        try{
            area.print();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnprintreceiptActionPerformed

    private void btnviewpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpaymentActionPerformed
        new view_payment(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnviewpaymentActionPerformed

     private void clearFields(){ 
    //clears the textfields
    
    txtstdid.setText("");
    txtcourse.setText("");
    txttrainer.setText("");
    txtmonth.setText("");
    txtfee.setText("");
    txtpay.setText("");
    txtbalance.setText("");
    area.setText("");
    
    
    //set the cursor back to the ID textfield
    txtpay.requestFocus();
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btncalculate;
    private javax.swing.JButton btngeneratereceipt;
    private javax.swing.JButton btnprintreceipt;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnviewpayment;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxpaymentid;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JLabel lblcourse;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblid1;
    private javax.swing.JLabel lblpay;
    private javax.swing.JLabel lblstdid;
    private javax.swing.JLabel lblstdid1;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lbltrainer;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtcourse;
    private javax.swing.JTextField txtfee;
    private javax.swing.JTextField txtmadeby;
    private javax.swing.JTextField txtmonth;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtstdid;
    private javax.swing.JTextField txttrainer;
    // End of variables declaration//GEN-END:variables
}
