/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jasmi
 */
public class charge_student extends javax.swing.JFrame {
    String username = "";
     String idstaff = "";
    /**
     * Creates new form charge_student
     */
    public charge_student(String user,String staffid) {
        initComponents();
        setTitle("Health Care Fees Payment System"); 
         this.setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        fillcomboid();
        fillcombocourse();
        fillcombotrainer();
        fillcombomonth();
        username = user;
        idstaff = staffid;
        txtfee.setEditable(false);
    }

     private void fillcomboid() {      
        String role = "Student";
        File file = new File("Profile.txt");
        
        Scanner sc;
            try {    
                sc = new Scanner(file);
                
       String temp;
       boolean found = false;
       while(sc.hasNext() && !found /*the system will stop running while it found the correct username and password*/){
           temp = sc.nextLine(); //read a line of text from file
           String[] tempArr;
            tempArr = temp.split (",");

               if (role.equals(tempArr[7])){
              //needed value in array
                String valueneeded = tempArr[0];
                String [] column = valueneeded.split(",");
                   for (String column1 : column) {
                   cbxstdid.addItem(column1);
               }
               }             
            }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(check_schedule.class.getName()).log(Level.SEVERE, null, ex);
            }    
      }

    private void fillcombocourse() {
         String course [] = {"<-- Select Course-->","Intellectual Disability", "Biostatistics in Public Health", "Medical Secretary", "Health Economics", "Fundamental of Advocacy in Health Policy"};
          for (int i = 0; i <course.length; i++) {
       cbxcourse.addItem(course[i]);
       }
    }
    
     private void fillcombotrainer() {      
        String role = "Trainer";
        File file = new File("Profile.txt");
        
        Scanner sc;
            try {    
                sc = new Scanner(file);
                
       String temp;
       boolean found = false;
       while(sc.hasNext() && !found /*the system will stop running while it found the correct username and password*/){
           temp = sc.nextLine(); //read a line of text from file
           String[] tempArr;
            tempArr = temp.split (",");

               if (role.equals(tempArr[7])){
              //needed value in array
                String valueneeded = tempArr[1];
                String [] column = valueneeded.split(",");
               for (String column1 : column) {
                   cbxtrainer.addItem(column1);
               }
               }             
            }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(check_schedule.class.getName()).log(Level.SEVERE, null, ex);
            }    
    }   

     private void fillcombomonth() {
          String month [] = {"<-- Select Month-->", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
      for (int i = 0; i < month.length; i++) {
          cbxmonth.addItem(month[i]);
     }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxcourse = new javax.swing.JComboBox<>();
        cbxstdid = new javax.swing.JComboBox<>();
        btnreturn = new javax.swing.JButton();
        lbltrainer = new javax.swing.JLabel();
        cbxtrainer = new javax.swing.JComboBox<>();
        btnclearing = new javax.swing.JButton();
        txtfee = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lbltitle1 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblcourse = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        lbldob = new javax.swing.JLabel();
        cbxmonth = new javax.swing.JComboBox<>();
        btntrainerschedule = new javax.swing.JButton();
        txtchargeid = new javax.swing.JTextField();
        lblchargeid = new javax.swing.JLabel();
        btnstdview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcourseActionPerformed(evt);
            }
        });

        cbxstdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxstdidActionPerformed(evt);
            }
        });

        btnreturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        lbltrainer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltrainer.setText("Trainer");

        btnclearing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnclearing.setText("Clear");
        btnclearing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearingActionPerformed(evt);
            }
        });

        txtfee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 99, 71));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Charge");

        lbltitle1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle1.setText("Student");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblid.setText("Student ID");

        lblcourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcourse.setText("Course");

        lblgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblgender.setText("Month");

        btnadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        lbldob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldob.setText("Fee");

        btntrainerschedule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntrainerschedule.setText("Trainer Schedule");
        btntrainerschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrainerscheduleActionPerformed(evt);
            }
        });

        txtchargeid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblchargeid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblchargeid.setText("Charge ID");

        btnstdview.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnstdview.setText("View Student");
        btnstdview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstdviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnstdview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btntrainerschedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblid)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltrainer)
                                    .addComponent(lblcourse)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbldob)
                                        .addComponent(lblgender))))
                            .addComponent(lblchargeid))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(cbxstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbxtrainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnclearing)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(cbxmonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbxcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtchargeid, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreturn)
                    .addComponent(btntrainerschedule)
                    .addComponent(btnstdview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtchargeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblchargeid))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(cbxstdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltrainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxtrainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgender)
                    .addComponent(cbxmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldob))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclearing, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcourseActionPerformed
       String course = (String) cbxcourse.getSelectedItem();
        try{
            File file = new File("Course.txt");
            Scanner sc = new Scanner(file);
            //read data from the file

            String temp;
            boolean found = false;

            while(sc.hasNext() && !found /*the system will stop running while it found the correct username and password*/){
                temp = sc.nextLine(); //read a line of text from file
                String[] tempArr;
                tempArr = temp.split (",");
                
                if (course.equals(tempArr[0])) {
                    txtfee.setText(tempArr[1]);

                    //txtfee.setEditable(false);
                }
            }
        }catch(FileNotFoundException ex) {
            ex.toString();
        }
    }//GEN-LAST:event_cbxcourseActionPerformed

    private void cbxstdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxstdidActionPerformed
         
    }//GEN-LAST:event_cbxstdidActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        new staff_button(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btnclearingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearingActionPerformed
        cbxstdid.setSelectedItem("");
        cbxcourse.setSelectedItem("");
        cbxtrainer.setSelectedItem("");
        cbxmonth.setSelectedItem("");
        txtfee.setText("");
    }//GEN-LAST:event_btnclearingActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        if (cbxstdid.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Student ID", "Incomplete Student ID", JOptionPane.ERROR_MESSAGE);
            //set cursor to the textbox
            txtfee.requestFocus();
        }
        else if (cbxcourse.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Student Course", "Incomplete Student Course", JOptionPane.ERROR_MESSAGE);
            txtfee.requestFocus();
        }
        else if (cbxtrainer.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Trainer Name", "Incomplete Trainer Name", JOptionPane.ERROR_MESSAGE);
            txtfee.requestFocus();
        }
        else if(cbxmonth.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(rootPane, "You must provide the month", "Incomplete Month ", JOptionPane.ERROR_MESSAGE);
            txtfee.requestFocus();

        }
        else if(txtfee.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "You must provide the Fee", "Incomplete Student Fee", JOptionPane.ERROR_MESSAGE);
            txtfee.requestFocus();

        }
        else{
            try{
                String id = (String) cbxstdid.getSelectedItem();
                String course = (String) cbxcourse.getSelectedItem();
                String trainer = (String) cbxtrainer.getSelectedItem();
                String month = (String) cbxmonth.getSelectedItem();

                charge_student1 charge = new charge_student1(txtchargeid.getText(),id,course,trainer,month,txtfee.getText());
                FileWriter myFile = new FileWriter("Charges.txt",true);
                PrintWriter pw = new PrintWriter(myFile);
                pw.println(charge.getStudentchargeID() + "," + charge.getStudentID()+ "," + charge.getStudentcourse() + "," + charge.getStudenttrainer() +  "," + charge.getStudentmonth()+ "," + charge.getStudentfee() + "," + "Student");
                
                
                System.out.println(txtchargeid);
                System.out.println(id);
                System.out.println(course);
                System.out.println(trainer);
                System.out.println(month);
                System.out.println(txtfee);
                
                pw.close();
                JOptionPane.showMessageDialog(rootPane, "Student charges added", "Add Successful", JOptionPane.INFORMATION_MESSAGE);
                // After closing the previous message dialog, ask user whether
                // to continue adding
                int YesNo = JOptionPane.YES_OPTION;
                if (JOptionPane.showConfirmDialog (null, "Do you want to add another record?","Add New", YesNo) == JOptionPane.YES_OPTION){
                    clearFields();

                }
                else{
                    this.dispose();
                    new staff_button(username,idstaff).setVisible(true);

                }
            }
            catch (IOException ex){
                JOptionPane.showMessageDialog(rootPane, ex.toString());
            }

        }

    }//GEN-LAST:event_btnaddActionPerformed

    private void btntrainerscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrainerscheduleActionPerformed
        new confirm_schedule(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btntrainerscheduleActionPerformed

    private void btnstdviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstdviewActionPerformed
        new view_student(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnstdviewActionPerformed
    private void clearFields(){ 
        //clears the textfields

        cbxstdid.setSelectedItem("");
       cbxcourse.setSelectedItem("");
       cbxtrainer.setSelectedItem("");
        cbxmonth.setSelectedItem("");
        txtfee.setText("");
        txtchargeid.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(charge_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(charge_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(charge_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(charge_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclearing;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnstdview;
    private javax.swing.JButton btntrainerschedule;
    private javax.swing.JComboBox<String> cbxcourse;
    private javax.swing.JComboBox<String> cbxmonth;
    private javax.swing.JComboBox<String> cbxstdid;
    private javax.swing.JComboBox<String> cbxtrainer;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblchargeid;
    private javax.swing.JLabel lblcourse;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lbltrainer;
    private javax.swing.JTextField txtchargeid;
    private javax.swing.JTextField txtfee;
    // End of variables declaration//GEN-END:variables
}
