/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author jasmi
 */
public class search_trainer extends javax.swing.JFrame {
    Scanner sc;
    String keyId;
    String username = "";
    String idstaff = "";
    /**
     * Creates new form search_trainer
     */
    public search_trainer(String user,String staffid) {
        initComponents();
        setTitle("Health Care Fees Payment System"); 
         this.setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
         txtname.setEditable(false);
        txtage.setEditable(false);
        txtgender.setEditable(false);
        txtdob.setEditable(false);
        txtusername.setEditable(false);
        txtpassword.setEditable(false);
        username = user;
        idstaff = staffid;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsearch = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        lbldob = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtgender = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lbltitle1 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        chkview = new javax.swing.JCheckBox();
        lblusername = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        btnreturn = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        lbldob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldob.setText("Date of Birth");

        lblid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblid.setText("ID");

        txtage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        txtgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 99, 71));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Search");

        lbltitle1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle1.setText("Trainer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltitle1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle1)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        txtdob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblpassword.setText("Password");

        lblage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblage.setText("Age");

        lblname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblname.setText("Name");

        lblgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblgender.setText("Gender");

        chkview.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkview.setText("View");
        chkview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkviewActionPerformed(evt);
            }
        });

        lblusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblusername.setText("Username");

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnreturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btndelete)
                        .addGap(20, 20, 20)
                        .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnreturn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblname)
                                    .addComponent(lblage)
                                    .addComponent(lblgender)
                                    .addComponent(lblid)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldob, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblpassword, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(lblusername))))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtid)
                                    .addComponent(txtdob)
                                    .addComponent(txtgender)
                                    .addComponent(txtage)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkview)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblid)
                    .addComponent(btnsearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblage)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblgender)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldob)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassword)
                    .addComponent(chkview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
      
         String role = "Trainer";
        try{
            boolean found = false;
            FileReader curFile = new FileReader("Profile.txt");
            BufferedReader br = new BufferedReader(curFile);
            sc = new Scanner(br);
            sc.useDelimiter("[,\n]");
            keyId = txtid.getText();

            while(sc.hasNext() && !found){
                String arr = sc.nextLine();
                String[] temparr = arr.split(",");
                if(txtid.getText().equalsIgnoreCase(temparr[0]) && role.equals(temparr[7])){
                    String trainername = temparr[1];
                    String trainerage = temparr[2];
                    String trainergender = temparr[3];
                    String trainerdob = temparr[4];
                    String trainerusername = temparr[5];
                    String trainerpassword = temparr[6];
                    
                     int YesNo = JOptionPane.YES_OPTION;
                    if (JOptionPane.showConfirmDialog (null, "Do you want to update?","Confirm Update", YesNo) == JOptionPane.YES_OPTION){
                    btndelete.setEnabled(false);
                    btnupdate.setEnabled(true);
                    }
                    else {
                    btnupdate.setEnabled(false);
                    btndelete.setEnabled(true);
                    }  
                    
                    txtname.setText(trainername);
                    txtage.setText(trainerage);
                    txtgender.setText(trainergender);
                    txtdob.setText(trainerdob);
                    txtusername.setText(trainerusername);
                    txtpassword.setText(trainerpassword);
                    
                    txtname.setEditable(true);
                    txtage.setEditable(true);
                    txtgender.setEditable(true);
                    txtdob.setEditable(true);
                    txtusername.setEditable(true);
                    txtpassword.setEditable(true);
                    
                    found = true;

                }
            }
            if(!found){
                JOptionPane.showMessageDialog(rootPane, "Cannot find trainer record with the ID. Please ensure the ID is correct");
                txtid.requestFocus();
            }
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(rootPane,"Error");
        }
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
         String editTerm = txtid.getText();
        String newname = txtname.getText();
        String newage = txtage.getText();
        String newgender = txtgender.getText();
        String newdob = txtdob.getText();
        String newusername = txtusername.getText();
        String newpassword = new String(txtpassword.getPassword());
        
        // put in a listtrainer
        ArrayList <String> tempArray = new ArrayList <>();

        try{
            File file = new File("Profile.txt");
            file.createNewFile();
            Scanner sc = new Scanner(file);
            String data;

            while((data = sc.nextLine()) != null){
                String[] tempData = data.split(",");
                if(editTerm.equals(tempData[0])){
                    tempArray.add(editTerm + "," + newname + "," + newage+ "," + newgender+ "," + newdob   + "," + newusername + "," + newpassword + "," + tempData[7] );
                }else{
                    tempArray.add(data);
                }
            }
            sc.close();
        }catch(Exception ex){
            ex.toString();
        }

        try{
            try(PrintWriter pr = new PrintWriter("Profile.txt")){
                for(String newFile : tempArray){
                    pr.println(newFile);
                }
                pr.close();
                JOptionPane.showMessageDialog(rootPane, "Your profile has been updated", "Update Successful", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new view_trainer(username,idstaff).setVisible(true);
                return;
            }
        }catch(Exception ex){
            ex.toString();
        }        

    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void chkviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkviewActionPerformed
        if(chkview.isSelected()){
            txtpassword.setEchoChar((char)0); //unmask the password
        }
        else{
            txtpassword.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_chkviewActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        new staff_button(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
         String removeTerm = txtid.getText();        
        // put in a listtrainer
        ArrayList <String> tempArray = new ArrayList <>();

        try{
            File file = new File("Profile.txt");
            file.createNewFile();
            Scanner sc = new Scanner(file);
            String data;

            while((data = sc.nextLine()) != null){
                String[] tempData = data.split(",");
                if(!removeTerm.equals(tempData[0])){
                    tempArray.add(data);
                }
            }
            sc.close();
        }catch(Exception ex){
            ex.toString();
        }

        try{
            try(PrintWriter pr = new PrintWriter("Profile.txt")){
                for(String newFile : tempArray){
                    pr.println(newFile);
                }
                pr.close();
                JOptionPane.showMessageDialog(rootPane, "Your profile has been deleted", "Delete Successful", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new view_trainer(username,idstaff).setVisible(true);
                return;
            }
        }catch(Exception ex){
            ex.toString();
        }        
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JCheckBox chkview;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
