/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp;

/**
 *
 * @author jasmi
 */
public class staff_button extends javax.swing.JFrame {

    /**
     * Creates new form staff_button
     */
    String username = "";
    String idstaff = "";
    public staff_button(String user, String staffid) {
        initComponents();
        setTitle("Health Care Fees Payment System"); 
        this.setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        username= user;
        idstaff = staffid;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntsearch = new javax.swing.JButton();
        lblstudent1 = new javax.swing.JLabel();
        btnstdview = new javax.swing.JButton();
        btnstdpayment = new javax.swing.JButton();
        btnstdadd = new javax.swing.JButton();
        lbltrainer = new javax.swing.JLabel();
        btnstdsearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        btntview = new javax.swing.JButton();
        btntadd = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btncharge = new javax.swing.JButton();
        btnviewpayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btntsearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btntsearch.setText("Search");
        btntsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntsearchActionPerformed(evt);
            }
        });

        lblstudent1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblstudent1.setText("Student");

        btnstdview.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnstdview.setText("View");
        btnstdview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstdviewActionPerformed(evt);
            }
        });

        btnstdpayment.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnstdpayment.setText("Payment");
        btnstdpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstdpaymentActionPerformed(evt);
            }
        });

        btnstdadd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnstdadd.setText("Add");
        btnstdadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstdaddActionPerformed(evt);
            }
        });

        lbltrainer.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltrainer.setText("Trainer");

        btnstdsearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnstdsearch.setText("Search");
        btnstdsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstdsearchActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 99, 71));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Function");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btntview.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btntview.setText("View");
        btntview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntviewActionPerformed(evt);
            }
        });

        btntadd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btntadd.setText("Add");
        btntadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaddActionPerformed(evt);
            }
        });

        btnlogout.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btncharge.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btncharge.setText("Charge");
        btncharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchargeActionPerformed(evt);
            }
        });

        btnviewpayment.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnviewpayment.setText("View Payment");
        btnviewpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lbltrainer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnlogout)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblstudent1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btntview, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btntadd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 20, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnstdview, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                .addComponent(btnstdsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnstdadd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btncharge, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnviewpayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnstdpayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(btntsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltrainer)
                    .addComponent(btnlogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntview)
                    .addComponent(btntadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntsearch)
                .addGap(63, 63, 63)
                .addComponent(lblstudent1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstdadd)
                    .addComponent(btnstdview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstdsearch)
                    .addComponent(btncharge))
                .addGap(18, 18, 18)
                .addComponent(btnstdpayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnviewpayment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntsearchActionPerformed
        new search_trainer(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btntsearchActionPerformed

    private void btnstdviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstdviewActionPerformed
        new view_student(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnstdviewActionPerformed

    private void btnstdaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstdaddActionPerformed
        new add_student(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnstdaddActionPerformed

    private void btnstdsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstdsearchActionPerformed
        new search_student(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnstdsearchActionPerformed

    private void btntviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntviewActionPerformed
        new view_trainer(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btntviewActionPerformed

    private void btntaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaddActionPerformed
        new add_trainer(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btntaddActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnstdpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstdpaymentActionPerformed
        new add_payment(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnstdpaymentActionPerformed

    private void btnchargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchargeActionPerformed
        new charge_student(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnchargeActionPerformed

    private void btnviewpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpaymentActionPerformed
      new view_payment(username,idstaff).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnviewpaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncharge;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnstdadd;
    private javax.swing.JButton btnstdpayment;
    private javax.swing.JButton btnstdsearch;
    private javax.swing.JButton btnstdview;
    private javax.swing.JButton btntadd;
    private javax.swing.JButton btntsearch;
    private javax.swing.JButton btntview;
    private javax.swing.JButton btnviewpayment;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblstudent1;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltrainer;
    // End of variables declaration//GEN-END:variables
}
