/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jasmi
 */
public class upload_schedule extends javax.swing.JFrame {
    String trainername = "";
    String username = "";
    String idtrainer = "";
    /**
     * Creates new form upload_schedule
     *
     * @param user
     * @param nametrainer
     */
     public upload_schedule(String user, String nametrainer, String trainerid) {
        initComponents();
        setTitle("Health Care Fees Payment System"); 
         this.setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        fillcombotime();
        fillcombocourse();
       trainername = nametrainer;
       username = user;
       idtrainer = trainerid;
        txttrainername.setText(nametrainer);
        txttrainername.setEditable(false);
    }
     
    private void fillcombotime() {
         String time [] = {"<-- Select Time-->", "10am - 12pm", "12.30pm - 2.30pm", "3pm - 5pm", "5.30pm - 7.30pm"};
      for (int i = 0; i < time.length; i++) {
          cbxtime.addItem(time[i]);
      }
    }
    private void fillcombocourse() {
         String course [] = {"<-- Select Course-->","Intellectual Disability", "Biostatistics in Public Health", "Medical Secretary", "Health Economics", "Fundamental of Advocacy in Health Policy"};
          for (int i = 0; i <course.length; i++) {
       cbxcourse.addItem(course[i]);
       }
          
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtname1 = new javax.swing.JTextField();
        lblname1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lbltitle1 = new javax.swing.JLabel();
        lblcourse = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        txtdate = new javax.swing.JTextField();
        cbxcourse = new javax.swing.JComboBox<>();
        lblvenue = new javax.swing.JLabel();
        txtvenue = new javax.swing.JTextField();
        txtfee = new javax.swing.JTextField();
        lblfee = new javax.swing.JLabel();
        cbxtime = new javax.swing.JComboBox<>();
        lblname = new javax.swing.JLabel();
        btnreturn = new javax.swing.JButton();
        txttrainername = new javax.swing.JTextField();
        btntrainerschedule = new javax.swing.JButton();

        txtname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblname1.setText("Name");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 99, 71));

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Add");

        lbltitle1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbltitle1.setText("Schedule");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbltitle1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        lblcourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcourse.setText("Course");

        lbldate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldate.setText("Date");

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltime.setText("Time");

        btnadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        txtdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        cbxcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcourseActionPerformed(evt);
            }
        });

        lblvenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblvenue.setText("Venue");

        txtvenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtfee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeeActionPerformed(evt);
            }
        });

        lblfee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblfee.setText("Fee");

        cbxtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtimeActionPerformed(evt);
            }
        });

        lblname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblname.setText("Trainer Name");

        btnreturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        txttrainername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btntrainerschedule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntrainerschedule.setText("View Schedule");
        btntrainerschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrainerscheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblvenue)
                                .addGap(52, 52, 52)
                                .addComponent(txtvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcourse)
                                    .addComponent(lblname)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblfee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbldate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbltime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxtime, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttrainername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntrainerschedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreturn)
                    .addComponent(btntrainerschedule))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcourse)
                    .addComponent(cbxcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltime)
                    .addComponent(cbxtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldate))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvenue)
                    .addComponent(txtvenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txttrainername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

         if(cbxcourse.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(rootPane, "You must provide the course", "Incomplete Course", JOptionPane.ERROR_MESSAGE);
            cbxcourse.requestFocus();

        }
        else if(cbxtime.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(rootPane, "You must provide the time", "Incomplete Course Time", JOptionPane.ERROR_MESSAGE);
            cbxtime.requestFocus();

        }
        else if(txtdate.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "You must provide the date", "Incomplete Course Date", JOptionPane.ERROR_MESSAGE);
            txtdate.requestFocus();

        }
        else if (txtfee.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "You must provide your fee", "Incomplete Course Fee", JOptionPane.ERROR_MESSAGE);
            txtfee.requestFocus();
        }
        else if (txtvenue.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the venue", "Incomplete Venue", JOptionPane.ERROR_MESSAGE);
            txtvenue.requestFocus();
        }
        else if (txttrainername.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Trainer Name", "Incomplete Trainer Name", JOptionPane.ERROR_MESSAGE);
            txttrainername.requestFocus();
        }
        else{
            try{
                String course = (String) cbxcourse.getSelectedItem();
                String time = (String) cbxtime.getSelectedItem();
                
                upload_schedule1 schedule = new upload_schedule1(course,time,txtdate.getText(),txtfee.getText(),txtvenue.getText(),txttrainername.getText());
                FileWriter myFile = new FileWriter("T001_schedule.txt",true);
                PrintWriter pw = new PrintWriter(myFile);
                pw.println(schedule.getStudentcourse()+ "," + schedule.getStudenttime()+ "," + schedule.getStudentdate()+ "," + schedule.getStudentfee() + "," + schedule.getStudentVenue()+ "," + schedule.getTrainername());

                pw.close();
                JOptionPane.showMessageDialog(rootPane, "Schedule details added", "Add Successful", JOptionPane.INFORMATION_MESSAGE);
                // After closing the previous message dialog, ask user whether
                // to continue adding
                int YesNo = JOptionPane.YES_OPTION;
                if (JOptionPane.showConfirmDialog (null, "Do you want to add another record?","Add New", YesNo) == JOptionPane.YES_OPTION){
                    clearFields();

                }
                else{
                    this.dispose();
                    new trainer_button(username,trainername,idtrainer).setVisible(true);
                }
            
            }      
        
               catch (IOException ex){
               JOptionPane.showMessageDialog(rootPane, ex.toString());
               }
           
        }
            
        
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeeActionPerformed

    private void cbxcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcourseActionPerformed
     
       String course = (String) cbxcourse.getSelectedItem();
        try{
        File file = new File("Course.txt");
        Scanner sc = new Scanner(file);
        //read data from the file
       
       String temp;
       boolean found = false;
       
       while(sc.hasNext() && !found /*the system will stop running while it found the correct username and password*/){
           temp = sc.nextLine(); //read a line of text from file
           String[] tempArr;
            tempArr = temp.split (",");
           if (course.equals(tempArr[0])) { 
               txtfee.setText(tempArr[1]);
               
               txtfee.setEditable(false);
                
           }
       }
       }catch(FileNotFoundException ex) {
               ex.toString();
       }
       
    }//GEN-LAST:event_cbxcourseActionPerformed

    private void cbxtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxtimeActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        new trainer_button(username,trainername,idtrainer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btntrainerscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrainerscheduleActionPerformed
        new own_schedule(username,trainername,idtrainer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btntrainerscheduleActionPerformed
private void clearFields(){ 
    //clears the textfields
    
    cbxcourse.setSelectedItem("<-- Select Course-->");
    cbxtime.setSelectedItem("<-- Select Time-->");
    txtdate.setText("");
    txtfee.setText("");
     txtvenue.setText("");
     txttrainername.setText("");
    
    //set the cursor back to the ID textfield
    txtvenue.requestFocus();
}

    private boolean checkEmpty(){
    if(cbxcourse.getSelectedItem().equals("")||cbxtime.getSelectedItem().equals("")||txtdate.getText().equals("")||txtfee.getText().equals("")||txtvenue.getText().equals("")||txttrainername.getText().equals("")){
        return true;       
    }
    else{ return false;}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upload_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upload_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upload_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upload_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btntrainerschedule;
    private javax.swing.JComboBox<String> cbxcourse;
    private javax.swing.JComboBox<String> cbxtime;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcourse;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblfee;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lblvenue;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtfee;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txttrainername;
    private javax.swing.JTextField txtvenue;
    // End of variables declaration//GEN-END:variables
}
